### ISSUE TITLE
How to test on Udacity dataset?

### ISSUE THREAD

**Issue by cs-sun** [coinse/sadl#4]

**Comment by jinhankim** [comment]
In our github repo, replication for Udacity experiment is not included, as our repo is focused on showing how SA and SC are computed. It was hard to upload all images as well as pre trained model for Udacity dataset, and also, testing Udacity dataset required the replication of DeepXplore and DeepTest. Please consult DeepXplore and DeepTest artefect and corresponding links in README. I think if you can download dataset and pre-trained model and follow the guideline, it is quite easy to test SA or SC using the code in this repo.
